# Telegram Bot platform
- platform: polling
  api_key: !secret telegram_api_key
  trusted_networks:
    - 192.168.1.0/24
    - 192.168.2.0/24
    - 192.168.3.0/24
    - 192.168.4.0/24
  allowed_chat_ids:
    - !secret telegram_chat_id_paul
    - !secret telegram_chat_id_irene
    - !secret telegram_chat_id_thuis
    - !secret telegram_chat_id_bud_hut