####################################################
#                                                  #
#                Jarvis Config                     #
#                                                  #
####################################################

# Home Assistant PB
homeassistant:
  name: Jarvis
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_altitude
  unit_system: metric
  temperature_unit: C
  currency: EUR
  time_zone: Europe/Amsterdam
  customize: !include customize.yaml
  allowlist_external_dirs:
    - /config/www/climacons
  external_url: "https://hass.io.bonnemaijers.net"
  internal_url: "https://hass.io.bonnemaijers.net"

# All includes for the HTTPS instance
http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  server_port: 443 
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.3.10

# HASS Configurations
config:
default_config:
energy:
cloud:
api:
websocket_api:

# Frontend Setup
frontend:
  themes: !include_dir_merge_named themes

# Integrations
spotify: !include integrations/spotify.yaml
spotcast: !include integrations/spotcast.yaml
telegram_bot: !include integrations/telegram.yaml
notify: !include integrations/notifications.yaml
rflink: !include integrations/rflink.yaml
home_connect: !include integrations/home_connect.yaml
google: !include integrations/google.yaml
media_player: !include integrations/google_tv.yaml
lyric: !include integrations/lyric.yaml
alarm_control_panel: !include integrations/alarm_control_panel.yaml
sun:

# Device Entities
camera: !include_dir_merge_list cameras
group: !include groups/groups.yaml
switch: !include_dir_merge_list switches
light: !include_dir_merge_list lights
sensor: !include_dir_merge_list sensors
binary_sensor: !include_dir_merge_list binary_sensors
template: !include_dir_merge_list templates
climate: !include_dir_merge_list climate

# Utility Meter Settings
utility_meter: !include logging/utility_meter.yaml

# Home Automation
automation: !include automations.yaml
scene: !include scenes.yaml
script: !include_dir_merge_named scripts
script gui: !include /config/scripts.yaml

# Text to speech
tts: 
  platform: google_translate

# Database Settings
recorder: !include db_settings/recorder.yaml

# Influx DB Settings
influxdb: !include db_settings/influxdb.yaml

# Compatibiltiy checker
# breaking_changes:

# Logging
# logger: !include logging/logger.yaml

rest_command:
  pihole_disable_60:
    url: !secret pihole_disable_60
  pihole_enable:
    url: !secret pihole_enable