esphome:
  name: master-bedroom-sensor
  comment: Master Bedroom Temp/Humid/Co2/HPASCAL Sensor

esp8266:
  board: nodemcuv2
  #restore_from_flash: true

preferences:
  #flash_write_interval: 1min

globals:
  - id: iaq_index
    type: int
    restore_value: no
    initial_value: '0'

wifi:
  ssid: "Obi WLAN Kenobi"
  password: !secret pb_std_pass
  domain: .bonnemaijers.net
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Master Bedroom Sensor"
    password: !secret pb_std_pass

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret pb_std_pass

# Enable OTA
ota:
  password: !secret pb_std_pass

# Variables
substitutions:
  name: master-bedroom-sensor
  friendly_name: "Master Bedroom Sensor"

# Diagnostic Sensors
binary_sensor:
  - platform: status
    name: "${friendly_name} Status"
    entity_category: diagnostic

# i2c Sensor
i2c:
  scan: true
  id: bus_a

# Timesync with home
time:
  - platform: homeassistant

sensor:
  - platform: hdc1080
    temperature:
      name: "Master Bedroom Temperatuur"
      id: temp
      force_update: true
    humidity:
      name: "Master Bedroom Vochtigheid"
      id: humi
      force_update: true
    address: 0x40
    update_interval: 60s
  - platform: ccs811
    eco2:
      name: "Master Bedroom eCO2"
      id: eco2
      force_update: true
    tvoc:
      name: "Master Bedroom TVOC"
      id: tvoc
      force_update: true
    temperature: temp
    humidity: humi
    baseline: 0xEC62
    address: 0x5A
    update_interval: 30s
  - platform: bmp085
    temperature:
      name: "Barometer Temperatuur"
      force_update: true
    pressure:
      name: "Luchtdruk"
      force_update: true
    address:  0x77
    update_interval: 60s

text_sensor:  
  - platform: version
    hide_timestamp: true
    name: "${friendly_name} ESPHome Version"
    entity_category: diagnostic
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP Address"
      icon: mdi:wifi
      entity_category: diagnostic
    ssid:
      name: "${friendly_name} Connected SSID"
      icon: mdi:wifi-strength-2
      entity_category: diagnostic
  - platform: template
    name: "Master Bedroom IAQ"
    icon: "mdi:air-filter"
    lambda: |-
      id(iaq_index) = 0;
      
      /*
       * Transform indoor humidity values to IAQ points according to Indoor Air Quality UK: 
       * http://www.iaquk.org.uk/
       */
      if (id(humi).state < 10 or id(humi).state > 90) {
        id(iaq_index) += 1;
      }
      else if (id(humi).state < 20 or id(humi).state > 80) {
        id(iaq_index) += 2;
      }
      else if (id(humi).state < 30 or id(humi).state > 70) {
        id(iaq_index) += 3;
      }
      else if (id(humi).state < 40 or id(humi).state > 60) {
        id(iaq_index) += 4;
      }
      else if (id(humi).state >= 40 and id(humi).state <= 60) {
        id(iaq_index) += 5;
      }
      
      /*
       * Transform eCO2 values to IAQ points according to Indoor Air Quality UK: 
       * http://www.iaquk.org.uk/
       */
      if (id(eco2).state <= 600) {
        id(iaq_index) += 5;
      }
      else if (id(eco2).state <= 800) {
        id(iaq_index) += 4;
      }
      else if (id(eco2).state <= 1500) {
        id(iaq_index) += 3;
      }
      else if (id(eco2).state <= 1800) {
        id(iaq_index) += 2;
      }
      else if (id(eco2).state > 1800) {
        id(iaq_index) += 1;
      }
      
      /*
       * Transform TVOC values to IAQ points according to German environmental guidelines: 
       * https://www.repcomsrl.com/wp-content/uploads/2017/06/Environmental_Sensing_VOC_Product_Brochure_EN.pdf
       */
      if (id(tvoc).state <= 65) {
        id(iaq_index) += 5;
      }
      else if (id(tvoc).state <= 220) {
        id(iaq_index) += 4;
      }
      else if (id(tvoc).state <= 660) {
        id(iaq_index) += 3;
      }
      else if (id(tvoc).state <= 2200) {
        id(iaq_index) += 2;
      }
      else if (id(tvoc).state > 2200) {
        id(iaq_index) += 1;
      }

      /*
       * Transform IAQ index to human readable text according to Indoor Air Quality UK: 
       * http://www.iaquk.org.uk/
       */
      ESP_LOGD("main", "Current IAQ index %d", id(iaq_index));
      
      if (id(iaq_index) <= 6) {
        return {"Ongezond"};
      }
      else if (id(iaq_index) <= 9) {
        return {"Slecht"};
      }
      else if (id(iaq_index) <= 12) {
        return {"Gemiddeld"};
      }
      else if (id(iaq_index) <= 14) {
        return {"Goed"};
      }
      else if (id(iaq_index) > 14) {
        return {"Uitstekend"};
      }
      
      return {};
    update_interval: 60s