esphome:
  name: sproutbox
  comment: Sproutbox
  
esp8266:
  board: nodemcuv2
  restore_from_flash: true

preferences:
  flash_write_interval: 1min

wifi:
  ssid: "Obi WLAN Kenobi"
  password: !secret pb_std_pass
  domain: .bonnemaijers.net
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sproutbox Sensor"
    password: !secret pb_std_pass

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret pb_std_pass

# Enable OTA
ota:
  password: !secret pb_std_pass

# Timesync with home
time:
  - platform: homeassistant
  
# Variables
substitutions:
  name: sproutbox
  friendly_name: "Sproutbox"

# Diagnostic Sensors
binary_sensor:
  - platform: status
    name: "${friendly_name} Status"
    entity_category: diagnostic

text_sensor:
  - platform: version
    hide_timestamp: true
    name: "${friendly_name} ESPHome Version"
    entity_category: diagnostic
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP Address"
      icon: mdi:wifi
      entity_category: diagnostic
    ssid:
      name: "${friendly_name} Connected SSID"
      icon: mdi:wifi-strength-2
      entity_category: diagnostic

switch:
  - platform: gpio
    name: "Sproutbox Blue Growlight"
    pin: 13
    inverted: True
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: gpio
    name: "Sproutbox Red Growlight"
    pin: 14
    inverted: True
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: gpio
    name: "Sproutbox Fan"
    pin: 12
    inverted: True
    restore_mode: RESTORE_DEFAULT_OFF